### ISSUE TITLE
Request for Inclusion of Research Papers in the Survey

### ISSUE THREAD

**Issue by skejriwal44** [UbiquitousLearning/Efficient_Foundation_Model_Survey#3]
Firstly, I wanted to extend my sincere appreciation for your exceptional survey paper on foundation models. 
Your comprehensive work has been incredibly insightful and valuable, especially for those of us focusing on the efficiency and scalability of these models.

I have been involved in research on the efficiency of generative models, particularly diffusion models. 
I would like to kindly request the inclusion of one of our recent papers in your survey:

**Approximate Caching for Efficiently Serving Diffusion Models**
Paper: [ArXiv:2312.04429](https://arxiv.org/abs/2312.04429)
Accepted at NSDI 2024

Additionally, I came across another work that aligns well with the direction of our research:

ReDi: Efficient Learning-Free Diffusion Inference via Trajectory Retrieval
Paper: [ArXiv:2302.02285](https://arxiv.org/abs/2302.02285)
Accepted at ICML 2023

Thank you once again for your outstanding contributions to the field. Your consideration of these papers would be greatly appreciated.

Best regards,
Shubham Agarwal
Adobe Research

**Comment by xumengwei** [comment]
Thanks for sharing. We'll include them in the next version.
